import 'reflect-metadata';
import { container } from 'tsyringe';
import { AuthServiceClient, AuthServiceToken } from './authService';
import { BlogServiceClient, BlogServiceToken } from './blogService';
import { ChallengeServiceClient, ChallengeServiceToken } from './challengeService';
import { ChatServiceClient, ChatServiceToken } from './chatService';
import { ConfigServiceClient, ConfigServiceToken } from './configService';
import { DirectoryServiceClient, DirectoryServiceToken } from './directoryService';
import { GroupServiceClient, GroupServiceToken } from './groupService';
import { MarketplaceServiceClient, MarketplaceServiceToken } from './marketplaceService';
import { GarageBikeServiceClient, GarageBikeServiceToken } from './garageBikeService';
import { MessageServiceClient, MessageServiceToken } from './messageService';
import { NewsServiceClient, NewsServiceToken } from './newsService';
import { RouteServiceClient, RouteServiceToken } from './routeService';
import { PlanServiceClient, PlanServiceToken } from './planService';
import { RideServiceClient, RideServiceToken } from './rideService';
import { StolenBikeServiceClient, StolenBikeServiceToken } from './stolenBikeService';
import { UserServiceClient, UserServiceToken } from './userService';
import { SocialServiceToken, SocialServiceClient } from './socialService';
import { LookupServiceClient, LookupServiceToken } from './lookupService';

container.registerSingleton(LookupServiceToken, LookupServiceClient);
container.registerSingleton(MarketplaceServiceToken, MarketplaceServiceClient);
container.registerSingleton(GarageBikeServiceToken, GarageBikeServiceClient);
container.registerSingleton(StolenBikeServiceToken, StolenBikeServiceClient);
container.registerSingleton(MessageServiceToken, MessageServiceClient);
container.registerSingleton(NewsServiceToken, NewsServiceClient);
container.registerSingleton(BlogServiceToken, BlogServiceClient);
container.registerSingleton(GroupServiceToken, GroupServiceClient);
container.registerSingleton(ChallengeServiceToken, ChallengeServiceClient);
container.registerSingleton(DirectoryServiceToken, DirectoryServiceClient);
container.registerSingleton(RouteServiceToken, RouteServiceClient);
container.registerSingleton(PlanServiceToken, PlanServiceClient);
container.registerSingleton(RideServiceToken, RideServiceClient);
container.registerSingleton(ConfigServiceToken, ConfigServiceClient);
container.registerSingleton(ChatServiceToken, ChatServiceClient);
container.registerSingleton(AuthServiceToken, AuthServiceClient);
container.registerSingleton(UserServiceToken, UserServiceClient);
container.registerSingleton(SocialServiceToken, SocialServiceClient);

export { container };
