import 'reflect-metadata';
import { container } from 'tsyringe';
import { AuthServiceClient } from './authService';
import { BlogServiceClient } from './blogService';
import { ChallengeServiceClient } from './challengeService';
import { ChatServiceClient } from './chatService';
import { ConfigServiceClient } from './configService';
import { DirectoryServiceClient } from './directoryService';
import { GroupServiceClient } from './groupService';
import { MarketplaceServiceClient } from './marketplaceService';
import { MessageServiceClient } from './messageService';
import { NewsServiceClient } from './newsService';
import { RouteServiceClient } from './routeService';
import { RideServiceClient } from './rideService';
import { SocialPostServiceClient } from './socialPostService';
import { SocialCommentServiceClient } from './socialCommentService';
import { SocialProfileServiceClient } from './socialProfileService';
import { StolenBikeServiceClient } from './stolenBikeService';
import { UserServiceClient } from './userService';
import { MarketplaceServiceToken } from './marketplaceService';
import { StolenBikeServiceToken } from './stolenBikeService';
import { MessageServiceToken } from './messageService';
import { NewsServiceToken } from './newsService';
import { BlogServiceToken } from './blogService';
import { SocialPostServiceToken } from './socialPostService';
import { SocialCommentServiceToken } from './socialCommentService';
import { GroupServiceToken } from './groupService';
import { SocialProfileServiceToken } from './socialProfileService';
import { ChallengeServiceToken } from './challengeService';
import { DirectoryServiceToken } from './directoryService';
import { RouteServiceToken } from './routeService';
import { RideServiceToken } from './rideService';
import { ConfigServiceToken } from './configService';
import { ChatServiceToken } from './chatService';
import { AuthServiceToken } from './authService';
import { UserServiceToken } from './userService';

container.registerSingleton(MarketplaceServiceToken, MarketplaceServiceClient);
container.registerSingleton(StolenBikeServiceToken, StolenBikeServiceClient);
container.registerSingleton(MessageServiceToken, MessageServiceClient);
container.registerSingleton(NewsServiceToken, NewsServiceClient);
container.registerSingleton(BlogServiceToken, BlogServiceClient);
container.registerSingleton(SocialPostServiceToken, SocialPostServiceClient);
container.registerSingleton(SocialCommentServiceToken, SocialCommentServiceClient);
container.registerSingleton(SocialProfileServiceToken, SocialProfileServiceClient);
container.registerSingleton(GroupServiceToken, GroupServiceClient);
container.registerSingleton(ChallengeServiceToken, ChallengeServiceClient);
container.registerSingleton(DirectoryServiceToken, DirectoryServiceClient);
container.registerSingleton(RouteServiceToken, RouteServiceClient);
container.registerSingleton(RideServiceToken, RideServiceClient);
container.registerSingleton(ConfigServiceToken, ConfigServiceClient);
container.registerSingleton(ChatServiceToken, ChatServiceClient);
container.registerSingleton(AuthServiceToken, AuthServiceClient);
container.registerSingleton(UserServiceToken, UserServiceClient);

export { container };
