/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/filter`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `/tools/report-stolen`; params?: Router.UnknownInputParams; } | { pathname: `/stolen/report`; params?: Router.UnknownInputParams; } | { pathname: `/travel/map`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/filter`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace`; params?: Router.UnknownOutputParams; } | { pathname: `/tools/report-stolen`; params?: Router.UnknownOutputParams; } | { pathname: `/stolen/report`; params?: Router.UnknownOutputParams; } | { pathname: `/travel/map`; params?: Router.UnknownOutputParams; } | { pathname: `/marketplace/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/marketplace/create${`?${string}` | `#${string}` | ''}` | `/marketplace/filter${`?${string}` | `#${string}` | ''}` | `/marketplace${`?${string}` | `#${string}` | ''}` | `/tools/report-stolen${`?${string}` | `#${string}` | ''}` | `/stolen/report${`?${string}` | `#${string}` | ''}` | `/travel/map${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/create`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace/filter`; params?: Router.UnknownInputParams; } | { pathname: `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `/tools/report-stolen`; params?: Router.UnknownInputParams; } | { pathname: `/stolen/report`; params?: Router.UnknownInputParams; } | { pathname: `/travel/map`; params?: Router.UnknownInputParams; } | `/marketplace/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/marketplace/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
